version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack-main
    hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"             # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"   # external services port range
    environment:
      - DEBUG=1
      - LEGACY_DIRECTORIES=1
      - AWS_DEFAULT_REGION=ap-southeast-1	  # Default region
      - AWS_ACCESS_KEY_ID=testUser          # Default access key
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh